version: '3.9'

services:

  mongo:
    image: bitnami/mongodb:4.4.4-debian-10-r41
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: password
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: pass
      MONGODB_DATABASE: testdb

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
